// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TweetSpot.Persistence.EF;

namespace TweetSpot.Persistence.EF.Migrations
{
    [DbContext(typeof(TweetSpotDbContext))]
    partial class TweetSpotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("TweetSpot.ServiceBus.Commands.ProcessIncomingTweet", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OrdinalCountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnparsedData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tweets");
                });
#pragma warning restore 612, 618
        }
    }
}
